// seed.js

import { createClient } from '@supabase/supabase-js';
import { faker } from '@faker-js/faker';
import 'dotenv/config'; // Load environment variables from .env

// --- CONFIGURATION ---
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
const TABLE_NAME = 'reports';
const NUMBER_OF_RECORDS = 100;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    console.error("Error: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in the .env file.");
    process.exit(1);
}

// Create a Supabase client with the Service Role Key (Bypasses RLS)
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// --- DATA GENERATION FUNCTION ---
/**
 * Generates a single fake report object using Faker.js.
 * Matches the 'reports' table schema you created.
 */
function createFakeReport() {
    return {
        // ID and created_at are generated by the database default values
        title: faker.hacker.phrase(), // Example: "synthesize primary array"
        description: faker.lorem.paragraphs(2),
        impact_score: faker.number.int({ min: 10, max: 999 }), // Three-digit score
        location: faker.location.city() + ', ' + faker.location.countryCode('alpha-2'),
        is_verified: faker.datatype.boolean({ probability: 0.8 }), // 80% chance of being verified
    };
}

// --- EXECUTION FUNCTION ---
async function seedDatabase() {
    console.log(`Starting to generate ${NUMBER_OF_RECORDS} dummy reports...`);

    // Generate the array of data
    const reportsToInsert = Array.from({ length: NUMBER_OF_RECORDS }, createFakeReport);

    console.log(`Inserting data into the '${TABLE_NAME}' table...`);

    // Perform the bulk insert
    const { data, error } = await supabase
        .from(TABLE_NAME)
        .insert(reportsToInsert)
        .select();

    if (error) {
        console.error('❌ Data seeding failed:', error.message);
        console.error('Details:', error.details);
        return;
    }

    console.log(`\n✅ Successfully inserted ${data.length} records into the '${TABLE_NAME}' table.`);
    console.log('--- Database Seeding Complete ---');
}

seedDatabase();